name: viash ns list
author: Data Intuitive
description: List a namespace containing many viash config files.
inputs:
  query:
    description: 'Filter which components get selected by component and namespace
      name. Can be a regex. Example: "^mynamespace/component1$".'
    required: false
  query_namespace:
    description: 'Filter which namespaces get selected by namespace name. Can be a
      regex. Example: "^mynamespace$".'
    required: false
  query_name:
    description: 'Filter which components get selected by component name. Can be a
      regex. Example: "^component1".'
    required: false
  src:
    description: 'A source directory containing viash config files, possibly structured
      in a hierarchical folder structure. Default: src/.'
    required: false
  runner:
    description: Acts as a regular expression to filter the runner ids specified in
      the found config files. If this is not provided, all runners will be used. If
      no runners are defined in a config, the executable runner will be used.
    required: false
  engine:
    description: Acts as a regular expression to filter the engine ids specified in
      the found config files. If this is not provided, all engines will be used. If
      no engines are defined in a config, the native engine will be used.
    required: false
  config_mod:
    description: Modify a viash config at runtime using config_mod.
    required: false
  colorize:
    description: 'Specify whether the console output should be colorized. If not specified,
      we attempt to detect this automatically. Possible values are: "true", "false",
      "auto".'
    required: false
  loglevel:
    description: 'Specify the log level in us. Possible values are: "error", "warn",
      "info", "debug", "trace".'
    required: false
  format:
    description: 'Which output format to use. Possible values are: "yaml", "json".'
    required: false
  parse_argument_groups:
    description: DEPRECATED. This is now always enabled. Whether or not to postprocess
      each component's argument_groups.
    required: false
  platform:
    description: Acts as a regular expression to filter the platform ids specified
      in the found config files. If this is not provided, all platforms will be used.
      If no platforms are defined in a config, the native platform will be used. In
      addition, the path to a platform yaml file can also be specified. Deprecated
      in Viash 0.9.0, will be removed in Viash 1.0.0.
    required: false
outputs:
  output:
    description: A list of all of the components found. By default this will be a
      yaml, unless the format argument was set to 'json'.
runs:
  using: node20
  main: index.js
