name: viash ns list
description: List a namespace containing many viash config files.
inputs:
  query:
    description: 'Filter which components get selected by component and namespace
      name. Can be a regex. Example: "^mynamespace/component1$".'
    required: false
  query_namespace:
    description: 'Filter which namespaces get selected by namespace name. Can be a
      regex. Example: "^mynamespace$".'
    required: false
  query_name:
    description: 'Filter which components get selected by component name. Can be a
      regex. Example: "^component1".'
    required: false
  src:
    description: 'A source directory containing viash config files, possibly structured
      in a hierarchical folder structure. Default: "src/".'
    required: false
  platform:
    description: Acts as a regular expression to filter the platform ids specified
      in the found config files. If this is not provided, all platforms will be used.
      If no platforms are defined in a config, the native platform will be used. In
      addition, the path to a platform yaml file can also be specified.
    required: false
  config_mod:
    description: Modify a viash config at runtime using dynamic config modding.
    required: false
  format:
    description: 'Which output format to use. Possible values are: "yaml", "json". Default is "yaml".'
    required: false
  parse_argument_groups:
    description: Whether or not to postprocess each component's argument groups.
    required: false
  output_file:
    required: false
    description: Path of a file to which the output will be written.
outputs:
  output:
    description: A list of all of the components found. By default this will be a
      yaml, unless the format argument was set to 'json'.
  output_file:
    description: >
      Path of a file to which the output was written (same as inputs.output_file).
      We recommend using this property for capturing the action's output because
      there is a limit in the object size that github actions can manage. Additionally,
      if you use this property instead of a static file path, changing the location of
      the output file will not require you to adjust settings for downstream actions as well.
runs:
  using: node16
  main: index.js
