# This script generates a github action given a Viash schema

library(tidyverse)

# parameters
skip_args <- c("parallel")
dest_file <- "ns-list/action.yml"
subcommands <- c("ns", "list")

#################### common code
# fetch schema
out <- system("viash export cli_schema --format json", intern = TRUE)
schema <- jsonlite::fromJSON(out, simplifyVector = FALSE)

# go down schema to find the right command
for (i in seq_along(subcommands)) {
  subcommand_names <- sapply(schema, function(li) li$name)
  schema <- schema[[which(subcommand_names == subcommands[[i]])]]

  if ("subcommands" %in% names(schema) && i < length(subcommands)) {
    schema <- schema$subcommands
  }
}

# construct yaml
selected_opts <- schema$opts[sapply(schema$opts, function(x) !x$name %in% skip_args)]
input_values <- sapply(selected_opts, function(opt) {
  descr <- opt$descr %>%
    str_replace_all("@\\[[^]]*\\]\\(([^\\)]*)\\)", "\\1") %>%
    str_replace_all(". *$", ".")

  choices_str <-
    if (!is.null(opt$choices)) {
      paste0(" Possible values are: \"", paste(opt$choices, collapse = "\", \""), "\".")
    } else {
      ""
    }
  out <- list(
    description = paste0(descr, choices_str),
    required = opt$required
  )
  setNames(list(out), opt$name)
})

input_values$project_directory <- list(
  description = "Path to the project directory. This is the directory where the project's `_viash.yaml` file is located. If not provided, the current working directory is used.",
  required = FALSE
)

input_values$output_file <- list(
  description = "Path of a file to which the output will be written. If not set, this action will create a file with a random name in `RUNNER_TEMP`.",
  required = FALSE
)

out <- list(
  name = schema$bannerCommand,
  author = "Data Intuitive",
  description = schema$bannerDescription,
  inputs = input_values,
  outputs = list(
    output = list(
      description = "The output of the 'viash ns list' command, which is a list of all of the components found. By default this will be a yaml, unless the format argument was set to 'json'."
    ),
    output_file = list(
      description = "Path of a file to which the output was written (same as `inputs.output_file``). We recommend using this property for capturing the action's output because there is a limit in the object size that github actions can manage. Additionally, if you use this property instead of a static file path, changing the location of the output file will not require you to adjust settings for downstream actions as well."
    ),
    output_matrix = list(
      description = "A simplified version of the output, which is a list of components with fields 'name', 'namespace', 'full_name', 'config', and 'dir'."
    )
  ),
  runs = list(
    using = "node20",
    main = "index.js"
  )
)

# write github action
handlers <- list(
  logical = function(x) {
    result <- ifelse(x, "true", "false")
    class(result) <- "verbatim"
    return(result)
  }
)
yaml_str <- yaml::as.yaml(
  out,
  handlers = handlers
)
out_str <- c(
  "########################################################",
  "#            DO NOT EDIT THIS FILE MANUALLY            #",
  "# Please run 'Rscript ns-list/generate_yml.R' instead  #",
  "########################################################",
  yaml_str
)
writeLines(out_str, dest_file)
