name: Check for concurrent PRs
author: Data Intuitive
description: >
  Assuming that an action is triggered by both a push event and a pull request, this action will:

    - Return 'true' if the branch is the default branch
    - Return 'true' if the event is not a push event
    - Return 'true' if the commit message contains 'ci force'
    - Return 'false' if a PR exists for the branch, else 'true'
outputs:
  run:
    description: 'Returns "true" if the branch has a PR and this run was not triggered by a push event, else "false".'
    value: ${{ steps.check.outputs.run }}
runs:
  using: 'composite'
  steps:
    - name: 'Check whether the branch has a PR and if this run was triggered by a push event'
      shell: bash
      id: check
      run: |
        # if the branch is the default branch, always run
        if [[ "$GITHUB_REF_NAME" == "$GITHUB_DEFAULT_BRANCH" ]]; then
          echo "run=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        # if the event is not a push event, always run
        if [[ "${{ github.event_name == 'push' }}" == "false" ]]; then
          echo "run=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        # if the commit message contains 'ci force', always run
        if [[ "${{ contains(github.event.head_commit.message, 'ci force') }}" == "true" ]]; then
          echo "run=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        # if a PR exists for the branch, do not run
        pull_request=$(gh pr list -R ${{ github.repository }} -H ${{ github.ref_name }} --json url --state open --limit 1 | jq '.[0].url')
        if [[ "$pull_request" == "null" ]]; then
          echo "run=true" >> $GITHUB_OUTPUT
        else
          echo "run=false" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
