name: 'Setup Viash'
author: 'Robrecht Cannoodt'
description: 'This action will setup Viash from the git repository https://github.com/viash-io/viash/'
inputs:
  version:
    description: 'The version of Viash to use. Either a release tag (eg. 0.6.0) or "develop" for latest built dev version. If missing, uses latest stable version.'
    required: false
  registry:
    description: 'Which Docker registry to use in the Docker image name.'
    required: false
  organisation:
    description: 'Which organisation name to use in the Docker image name.'
    required: false
  target_image_source:
    description: 'Which image source to specify in the component builds.'
    required: false
outputs:
  version:
    description: 'The installed version of viash.'
    value: ${{ steps.install-viash.outputs.version }}
runs:
  using: 'composite'
  steps: 
    - name: 'Install Viash'
      id: install-viash 
      env: 
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        # process parameters
        extra_params=( )
        if [ ! -z "${{inputs.version}}" ]; then 
          extra_params+=( "--tag" "${{inputs.version}}" )
        fi
        if [ ! -z "${{inputs.registry}}" ]; then 
          extra_params+=( "--registry" "${{inputs.registry}}" )
        fi
        if [ ! -z "${{inputs.organisation}}" ]; then 
          extra_params+=( "--organisation" "${{inputs.organisation}}" )
        fi
        if [ ! -z "${{inputs.target_image_source}}" ]; then 
          extra_params+=( "--target_image_source" "${{inputs.target_image_source}}" )
        fi

        # create dir
        mkdir -p "$HOME/.local/bin"

        # install viash
        curl -fsSL get.viash.io | bash -s -- "${extra_params[@]}" --bin "$HOME/.local/bin"

        # add dir to path
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
        # check version
        viash -v | sed 's#viash #version=#;s# (c).*##' >> $GITHUB_OUTPUT

        echo "Viash Installed !"
      shell: bash
