name: 'Setup Viash'
author: Data Intuitive
description: 'This action will setup Viash from the git repository https://github.com/viash-io/viash/'
inputs:
  version:
    description: 'The version of Viash to use. Either a release tag (eg. 0.6.0) or "develop" for latest built dev version. If missing, uses latest stable version.'
    required: false
outputs:
  version:
    description: 'The installed version of viash.'
    value: ${{ steps.install-viash.outputs.version }}
runs:
  using: 'composite'
  steps: 
    - name: 'Install Viash'
      id: install-viash 
      env: 
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        # process parameters
        extra_params=( )
        if [ ! -z "${{inputs.version}}" ]; then 
          extra_params+=( "--tag" "${{inputs.version}}" )
        fi

        # create dir
        mkdir -p "$HOME/.local/bin"

        # install viash
        curl -fsSL dl.viash.io | bash -s -- "${extra_params[@]}"; mv viash "$HOME/.local/bin"

        # add dir to path
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
        # check version
        viash -v | sed 's#viash #version=#;s# (c).*##' >> $GITHUB_OUTPUT

        echo "Viash Installed !"
      shell: bash
