name: 'Setup Viash'
author: Data Intuitive
description: 'This action will setup Viash from the git repository https://github.com/viash-io/viash/'
inputs:
  version:
    description: 'The version of Viash to use. Either a release tag (eg. 0.6.0) or "@develop" for latest development version. If missing, uses latest stable version.'
    required: false
outputs:
  version:
    description: 'The installed version of viash.'
    value: ${{ steps.install-viash.outputs.version }}
runs:
  using: 'composite'
  steps: 
    - name: 'Install Viash'
      id: install-viash 
      env: 
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        # process parameters
        extra_params=( )
        if [ ! -z "${{inputs.version}}" ]; then 
          extra_params+=( "--tag" "${{inputs.version}}" )
        fi

        # create dir
        mkdir -p "$HOME/.local/bin"

        # download installer script
        # note: this sometimes times out so pointing directly to the latest release
        # wget https://dl.viash.io -O $RUNNER_TEMP/viash_install || \
        wget https://github.com/viash-io/viash/releases/latest/download/viash_install -O $RUNNER_TEMP/viash_install
        
        # install viash
        bash "$RUNNER_TEMP/viash_install" "${extra_params[@]}" --output "$HOME/.local/bin/viash"
        rm "$RUNNER_TEMP/viash_install"

        # add dir to path
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
        # check version
        viash -v | sed 's#viash #version=#;s# (c).*##' >> $GITHUB_OUTPUT

        echo "Viash Installed !"
      shell: bash
