---
title: generate-documentation-qmd
format: gfm
---

```{r}
#| include: false
library(tidyverse)
action <- yaml::read_yaml("action.yml")
```

`r action$description`

### Inputs available

```{r}
#| echo: false
lines <- map_chr(names(action$inputs), function(name) {
  input <- action$inputs[[name]]
  required <- ifelse (input$required %||% FALSE, "", "_(Optional)_ ")
  glue::glue("* `{name}`: {required}{input$description}")
})
knitr::asis_output(paste0(lines, collapse = "\n"))
```

### Outputs

```{r}
#| echo: false
lines <- map_chr(names(action$outputs), function(name) {
  output <- action$outputs[[name]]
  glue::glue("* `{name}`: {output$description}")
})
knitr::asis_output(paste0(lines, collapse = "\n"))
```


## Examples

```yaml
name: demo of generate-documentation-qmd

on:
  pull_request:

jobs:
  demo:
    runs-on: ubuntu-latest
    
    steps:
    - uses: viash-io/viash-actions/setup@v3
    - uses: actions/checkout@v3
    - uses: viash-io/viash-actions/generate-documentation-qmd@v3
      with:
        input_dir: src
        output_dir: /website/components
        dest_path: "{type}s/{namespace}/{name}.qmd"
        git_repo: openpipelines-bio/openpipelines
        token: ${{ secrets.GTHB_PAT }}
        tools_version: main_build
```

# Example template

````markdown

---
title: "{{functionality.info.name}}"
namespace: "{{functionality.info.namespace}}"
description: "{{functionality.info.short_description}}"
type: "{{info.type}}"
toc: false
---

::: {.column-margin}

### Info

ID: `{{functionality.name}}`{{'  '}}
{%- if functionality.namespace is defined %}
Namespace: `{{functionality.namespace}}`
{%- endif %}

{%- if render.source_url is defined %}

### Links
[Source]({{render.source_url}}){.btn-action .btn-sm .btn-info .btn role="button"}
{%- endif %}

:::

{{functionality.description}}

## Example commands

You can run the pipeline using `nextflow run`.

### View help

You can use `--help` as a parameter to get an overview of the possible parameters.

```bash
nextflow run {{par.git_repo}} \
  -r {{par.git_tag}} -latest \
  -main-script {{render.nf_path}} \
  --help
```

### Run command

<details>
<summary>Example of `params.yaml`</summary>
```yaml
{{render.params_yaml}}
```
</details>

```bash
nextflow run {{par.git_repo}} \
  -r {{par.git_tag}} -latest \
  -profile docker \
  -main-script {{render.nf_path}} \
  -params-file params.yaml
```

:::{.callout-note}
Replace `-profile docker` with `-profile podman` or `-profile singularity` depending on the desired backend.
:::

## Argument group{% if render.argument_groups|length > 1 %}s{% endif %}

{%- for group in render.argument_groups %}

### {{group.name}}

{%- if group.description is defined %}

{{group.description}}
{% endif %}

{{group.table_md}}
{% endfor %}

{%- if functionality.authors is defined %}
## Authors
{% for author in functionality.authors %}
  * {{author.name}}
    {%- if author.props.github is defined -%}
      {% raw %} [{{< fa brands github >}}{% endraw %}](https://github.com/{{author.props.github}})
    {%- endif -%}
    {%- if author.props.orcid is defined -%}
      {% raw %} [{{< fa brands orcid >}}{% endraw %}](https://orcid.org/{{author.props.orcid}})
    {%- endif -%}
    {%- if author.roles is defined and author.roles is not string -%}
      {{' '}}({{author.roles|join(", ")}})
    {%- endif -%}
    {%- if author.roles is defined and author.roles is string -%}
      {{' '}}({{author.roles}})
    {%- endif -%}
{% endfor %}
{% endif %}

{%- if render.graph is defined %}
## Visualisation

```{mermaid}
%%| column: screen-inset-shaded
{{render.graph}}
```
{%endif %}

````